version: "1.0"
info:
  model: int-scaffold
packages:
- name: MR_UKI2Project
  gitServerName: MR_UKI_Github
  gitUrl: https://github.com/mreys
  gitUsername: mreys
  gitBranch: main
services:
- serviceName: project.mr_uki2.integrations:DebugLogger
  packages:
  - name: MR_UKI2Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
